/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author I SEvEN
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        burger_q = new javax.swing.JTextField();
        roasted_q = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kabab_q = new javax.swing.JTextField();
        menu1 = new javax.swing.JComboBox<>();
        nextmenu = new javax.swing.JButton();
        backtohome1 = new javax.swing.JButton();
        btn_order = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\I SEvEN\\Documents\\NetBeansProjects\\Restaurant\\bergur.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter quantity :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\I SEvEN\\Documents\\NetBeansProjects\\Restaurant\\kabab.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter quantity :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(burger_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, -1));
        getContentPane().add(roasted_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 70, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\I SEvEN\\Documents\\NetBeansProjects\\Restaurant\\roastedm.jpg")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter quantity :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        getContentPane().add(kabab_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 70, -1));

        menu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 180, 30));

        nextmenu.setText("Next");
        nextmenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nextmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextmenuActionPerformed(evt);
            }
        });
        getContentPane().add(nextmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 80, 30));

        backtohome1.setText("Back");
        backtohome1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backtohome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtohome1ActionPerformed(evt);
            }
        });
        getContentPane().add(backtohome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 80, 30));

        btn_order.setText("Order");
        getContentPane().add(btn_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 443, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\I SEvEN\\Documents\\NetBeansProjects\\Restaurant\\menu.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backtohome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtohome1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        new Restaurant().setVisible(true);
    }//GEN-LAST:event_backtohome1ActionPerformed

    private void nextmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextmenuActionPerformed


        // TODO add your handling code here:
        
        
        this.dispose();
        new menu2().setVisible(true);
    }//GEN-LAST:event_nextmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtohome1;
    private javax.swing.JButton btn_order;
    private javax.swing.JTextField burger_q;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField kabab_q;
    private javax.swing.JComboBox<String> menu1;
    private javax.swing.JButton nextmenu;
    private javax.swing.JTextField roasted_q;
    // End of variables declaration//GEN-END:variables
}
